# Generated by Django 3.0.3 on 2020-03-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_add_projects_and_issues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='rate',
        ),
    ]
